version: "3.7"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  setup:
    build: .
    depends_on:
      - elastic
    command: >
      bash -c "python3 -m src.scripts.wait --host=elastic && ./scripts/create_index.py --host=elastic --name=documents --file=data/elasticsearch/index.json && python3 -m src.scripts.insert --host=elastic --index=documents --file=data/ca.json"

  app:
    build: ./app
    working_dir: /home/node/app
    volumes:
      - ./app/src:/home/node/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER=localhost:5000
    command: "npm start"

  flask:
    build: .
    depends_on:
      - elastic
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - ELASTIC_HOST=elastic
      - ELASTIC_INDEX=documents
    command: >
      bash -c "MODEL_NAME_OR_PATH=$${MODEL_CACHE}/incorpbot/$${INCORPBOT_MODEL} WORD_EMBEDDING_MODEL=$${MODEL_CACHE}/glove/$${GLOVE_MODEL} flask run --host=0.0.0.0"

  query:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - elastic
    command: >
      bash -c "python3 -m src.scripts.query --host=elastic --index=documents --model_name_or_path=$${MODEL_CACHE}/incorpbot/$${INCORPBOT_MODEL} --verbose_logging"

volumes:
  esdata:
    driver: local
