version: "3.7"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  setup:
    build: .
    depends_on:
      - elastic
    command: >
      bash -c "
        curl -X DELETE http://elastic:9200/documents && \
        curl -X DELETE http://elastic:9200/classes && \
        python3 -m src.scripts.wait --host=elastic &&
        python3 -m src.scripts.create_index --host=elastic --name=documents --file=data/elasticsearch/documents.json &&
        python3 -m src.scripts.create_index --host=elastic --name=classes --file=data/elasticsearch/classes.json &&
        python3 -m src.scripts.insert --host=elastic --index=documents --file=data/*.json --model=$${MODEL_CACHE}/use --spacy_model=$${SPACY_MODEL} &&
        python3 -m src.scripts.classification --host=elastic --index=classes --file=data/dialog.csv --model=$${MODEL_CACHE}/use
      "

  app:
    build: ./app
    working_dir: /home/node/app
    volumes:
      - ./app/src:/home/node/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER=localhost:5000
    command: "npm start"

  build_app:
    build: ./app
    working_dir: /home/node/app
    volumes:
      - ./app/src:/home/node/app/src
      - ./app/src/build:/home/node/app/src/build
    environment:
      - REACT_APP_SERVER=localhost:5000
    command: "npm run-script build"

  flask:
    build: .
    depends_on:
      - elastic
      - redis
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - ELASTIC_HOST=elastic
      - ELASTIC_INDEX=documents
      - REDIS_HOST=redis
    command: >
      bash -c "MODEL_NAME_OR_PATH=$${MODEL_CACHE}/incorpbot/$${INCORPBOT_MODEL} SENTENCE_EMBEDDING_MODEL=$${MODEL_CACHE}/use flask run --host=0.0.0.0"

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  query:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - elastic
    command: >
      bash -c "python3 -m src.scripts.query --host=elastic --index=documents --sentence_embedding_model=$${MODEL_CACHE}/use --model_name_or_path=$${MODEL_CACHE}/incorpbot/$${INCORPBOT_MODEL} --spacy_model=$${SPACY_MODEL} --verbose_logging --version_2_with_negative"

volumes:
  esdata:
    driver: local
