apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incorpbot.fullname" . }}
  labels:
    {{- include "incorpbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "incorpbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incorpbot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "incorpbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /ping
          #     port: http
          env:
            - name: MODEL_NAME_OR_PATH
              value: /root/.cache/torch/incorpbot/squad-2.0
            - name: SENTENCE_EMBEDDING_MODEL
              value: /root/.cache/torch/use
            - name: FLASK_APP
              value: app
            - name: ELASTIC_HOST
              value: elastic
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_INDEX
              value: documents
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: ELASTIC_USER
              value: elastic
            - name: ELASTIC_PASSWORD
              {{- toYaml .Values.password | nindent 14 -}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
