# Default values for elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

nodeSet:
  name: default
  master: true
  data: true
  ingress: true
  allow_mmap: false
  storage: 5G
