# Default values for elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9200

ingress:
  enabled: false

resources:
  limits:
    cpu: 2
    memory: 2G
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
